### ISSUE TITLE
Assignment 03 need to be approved

### ISSUE THREAD

**Issue by pipi0620** [Webbprogrammering/websoft#8]
1.Result should be displayed in the web page in a HTML table(some mistake)
2.Stop moveable object moving outside of the screen.(have trouble in it)

**Comment by mosbth** [comment]
Do you have a question regarding A03?
https://github.com/Webbprogrammering/websoft/wiki/Use-JavaScript-to-make-your-website-dynamic

**Comment by pipi0620** [comment]
> Do you have a question regarding A03?
> https://github.com/Webbprogrammering/websoft/wiki/Use-JavaScript-to-make-your-website-dynamic

Have difficulty in display the result in HTML table in requirements of grade 3.

**Comment by mosbth** [comment]
Yes, could you explain what dfficulties you have?

You could also provide a link to your page on GitHub pages as a reference, that makes it easier to see what you are trying to do.

**Comment by pipi0620** [comment]
Solved these problem
